- name: Deploy Docker app to Azure
  hosts: localhost
  connection: local
  vars:
    az_resource_group: "app-dashboard-rg"
    az_acr_name: "appdashboardacr"
    image_name: "dashboard"
    image_tag: "latest"
  
  tasks:
    - name: Login to Azure
      command: az login
      register: az_login
      changed_when: false
      
    - name: Build and tag Docker image
      command: docker build -t {{ image_name }}:{{ image_tag }} .
      args:
        chdir: "{{ playbook_dir }}/.."
      
    - name: Login to Azure Container Registry
      command: az acr login --name {{ az_acr_name }}
      
    - name: Tag image for ACR
      command: docker tag {{ image_name }}:{{ image_tag }} {{ az_acr_name }}.azurecr.io/{{ image_name }}:{{ image_tag }}
      
    - name: Push image to ACR
      command: docker push {{ az_acr_name }}.azurecr.io/{{ image_name }}:{{ image_tag }}
      
    - name: Configure App Service for Streamlit
      command: az webapp config appsettings set --name app-dashboard-service --resource-group {{ az_resource_group }} --settings WEBSITES_PORT=8501 PORT=8501
      
    - name: Restart Web App
      command: az webapp restart --name app-dashboard-service --resource-group {{ az_resource_group }}
